export interface NavEntry { key: string; label: string; safaricom: string | null; path: string; icon: string; phase: 1 | 2 | 3 | 4 | 5; available: boolean }
export interface NotPossibleItem { key: string; title: string; what: string; why: string; portalPath: string; ussd?: string }

export const copy = {
  qr: {
    title: 'QR codes', safaricom: 'Dynamic QR',
    intro: 'Let a customer scan a code to pay your organisation with M-Pesa.',
    payee: 'Paid to', shortcode: 'Shortcode', reference: 'Payment reference', referenceHint: 'An order or account reference, up to 32 characters.',
    type: 'How customers pay', paybill: 'Pay Bill', till: 'Buy Goods (till)',
    amount: 'Amount (KES)', customerAmount: 'Customer enters the amount',
    generate: 'Create QR code', generating: 'Creating the code…', download: 'Download QR image',
    imageAlt: 'M-Pesa payment QR code', ready: 'QR code ready',
    scan: 'Ask the customer to scan this code with their M-Pesa app and check the payee before paying.',
    unpaid: 'Creating or scanning a code does not confirm payment. Check your M-Pesa payment confirmation.',
    sandbox: 'Test money — this code cannot collect real money.', production: 'Real money',
    noPermission: 'You need permission to create QR codes. Ask the owner.',
    noResponse: 'No usable response was received.', retry: 'Check your settings and connection, then try again.',
    badResponse: 'Studio could not display the QR image. Create a new code.',
  },
  appName: 'daraja-studio',
  app: {
    loading: 'Loading…',
    errorTitle: 'Cannot reach the studio server.',
    errorBody: 'Check that the server is running, then try again.',
    retry: 'Try again',
    navLabel: 'Main',
  },
  landing: {
    title: 'Daraja Studio',
    tagline: 'Simplified console for your M-Pesa paybill or till.',
    login: 'Log in',
    signup: "Create your organisation's account",
    smallPrint: 'Test money is free. Real money costs from KES 999 a month after 7 days free. Or run it yourself for free:',
    repoLabel: 'github.com/kepas-tech/daraja-studio',
    repoHref: 'https://github.com/kepas-tech/daraja-studio',
  },
  org: {
    name: 'Organisation',
    // Plain English in the pill; Safaricom's own word sits under it in grey.
    badge: { sandbox: 'Test money', production: 'Real money' } as Record<string, string>,
    badgeSafaricom: { sandbox: 'Sandbox', production: 'Production' } as Record<string, string>,
    suspended: 'This organisation is read-only. Nothing has been deleted. You can still look at everything. Contact the service administrator to restore access.',
    signedUp: 'Signed up',
    verifiedOn: 'Verified by Safaricom',
    status: {
      pending: 'Signing up', creds_ok: 'Signing up', operator_probing: 'Waiting for Safaricom',
      failed: 'Sign-up did not finish', verified: 'Verified', suspended: 'Read-only', closed: 'Closed',
    } as Record<string, string>,
  },
  whitelist: {
    title: 'Safaricom must allow this service to act for your shortcode',
    before: 'Before Safaricom accepts requests from this service, your organisation must whitelist our address with Safaricom:',
    ask: (shortcode: string) => `Ask Safaricom's API support team or your account manager to add it for shortcode ${shortcode}.`,
    askNoShortcode: "Ask Safaricom's API support team or your account manager to add it for your shortcode.",
    until: 'Until then Safaricom refuses every request with code 403.002.1001.',
    sandbox: 'Sandbox does not need this.',
  },
  signup: {
    email: {
      title: 'Confirm your email',
      sentTo: 'Your sign-up email address:',
      instructions: 'Enter the six-digit code from our email, or open its confirmation link. Both expire in 10 minutes.',
      deliveryFailed: 'We could not send your confirmation email. Your account is saved. Request another email below.',
      code: 'Six-digit code',
      verify: 'Confirm my email',
      help: 'Check your spam folder too. A new email replaces the previous code and link. Never share either with anyone.',
      resend: 'Send another email',
      wait: 'Wait one minute before sending again',
      usedLink: 'I used the email link',
      notYet: 'Your email is still waiting for confirmation. Enter the code or open the link from your email.',
      invalidLink: 'This confirmation link is missing or incomplete.',
      confirmed: 'Your email is confirmed',
      returnToSignup: 'Return to your sign-up screen to continue. If you opened this on another device, log in with your email and password.',
      linkHelp: 'Return to the sign-up screen and request another email.',
      checking: 'Checking your confirmation link…',
      continue: 'Continue sign-up',
    },
    title: "Create your organisation's account",
    steps: ['Your account', 'Confirm email', 'What you need', 'Your Daraja app', 'Your shortcode', 'Your passkey', 'Your API operator', 'Waiting for Safaricom'],
    back: 'Back',
    loading: 'Loading…',
    /**
     * Asked in the business's own words, never in Safaricom's. Somebody setting up a shop should not
     * have to know what B2C or STK mean to answer correctly — the answers decide which credentials
     * are asked for later, so getting the wording right here is what keeps the rest of the wizard
     * from asking for things nobody needs.
     */
    uses: {
      title: 'What will you use M-Pesa for?',
      intro: 'Tick everything you need. You can change this later in Settings.',
      payOut: 'Pay money out to people',
      payOutHelp: 'Salaries, suppliers, refunds. Money leaves your account and arrives on a phone.',
      payOutSafaricom: 'Safaricom calls this B2C',
      collect: 'Ask customers to pay you on their phone',
      collectHelp: 'You enter their number and the amount. Their phone asks for their M-Pesa PIN.',
      collectSafaricom: 'Safaricom calls this M-Pesa Express, or STK Push',
      nothing: 'Choose at least one, so we know what to set up.',
      next: 'Continue',
    },
    passkey: {
      title: 'Your passkey',
      intro: 'This lets you ask customers to pay. Copy it from the Daraja portal, under Lipa Na M-Pesa Online for this shortcode.',
      field: 'Passkey',
      phone: 'Your own phone number',
      phoneHelp: 'We send one test to this number. Use your own, not a customer’s.',
      testTitle: 'We will test it now',
      testBody: 'Your phone will ask for your M-Pesa PIN for KES 1. You can cancel it — we only need to see that Safaricom accepted it.',
      test: 'Save and test',
      testing: 'Asking Safaricom…',
      proven: 'Your passkey works. Safaricom accepted the request.',
      provenNote: 'If you cancelled the prompt, that is fine. Nothing was taken.',
      failedTitle: 'That passkey did not work.',
      failedBody: 'Safaricom refused it, so no prompt was sent to your phone and nothing was charged. Check you copied the passkey for this exact shortcode, then try again.',
      retry: 'Try another passkey',
      next: 'Continue',
    },
    account: {
      title: "Create your organisation's account",
      orgName: 'Organisation name',
      displayName: 'Your name',
      email: 'Your e-mail address (this is how you will log in)',
      password: 'Choose a password (at least 12 characters)',
      environment: 'Where will you use Studio?',
      sandbox: 'Test money (Safaricom sandbox). Free, for trying things out.',
      production: "Real money (production). Needs your organisation's M-Pesa shortcode and Daraja app. Free for 7 days, then from KES 999 a month.",
      button: 'Continue',
      haveAccount: 'Already have an account?',
      login: 'Log in',
    },
    daraja: {
      title: 'Your Daraja app',
      intro: 'Studio talks to Safaricom through a Daraja app that belongs to you. Paste its key and secret.',
      safaricom: 'Safaricom calls these Consumer Key and Consumer Secret.',
      sandboxHint: "On Safaricom's Daraja developer portal, create an app with the test shortcode. The key and secret are on its page.",
      productionHint: 'Use the production key and secret from the Daraja portal. Studio checks them with Safaricom now and never shows the secret again.',
      key: 'Consumer key',
      secret: 'Consumer secret',
      button: 'Check with Safaricom',
    },
    shortcode: {
      title: 'Your shortcode',
      intro: "Type your organisation's paybill or till number. Studio asks Safaricom for the name registered to it so you can check it is yours.",
      field: 'Paybill or till number',
      safaricom: 'Safaricom calls this the Shortcode',
      sandboxHint: "This is Safaricom's shared test shortcode. Keep it unless your sandbox app uses another.",
      sandboxDefault: '174379',
      check: 'Ask Safaricom',
      asking: 'Asking Safaricom…',
      knownAs: (name: string) => `Safaricom knows this shortcode as: ${name}. Is this your organisation?`,
      noAnswer: 'Safaricom gave no answer for this shortcode. Try again.',
      yes: 'Yes, continue',
      no: 'No, go back',
      skip: 'Continue without the name check. The operator test in the next step must still pass.',
      confirmed: 'Saved. Safaricom has your shortcode for this organisation.',
    },
    operator: {
      title: 'Your API operator',
      intro: 'This is the M-Pesa organisation-portal user allowed to move money through the API. Studio turns its password into a Security Credential straight away and never keeps the password.',
      safaricom: 'Safaricom calls this an Organization Operator',
      mode: 'How will you add this operator?',
      modeCredential: 'I already generated a Security Credential on the Daraja portal',
      modePassword: 'I have the operator password and the Safaricom certificate',
      name: 'Operator name',
      password: 'Operator password',
      credential: 'Or paste a Security Credential from the Daraja portal',
      whereCredential: 'Daraja portal › Test Credentials › Generate Security Credential.',
      cert: 'Safaricom certificate for this environment (paste the whole file)',
      button: 'Test with Safaricom',
    },
    waiting: {
      title: 'Waiting for Safaricom',
      intro: 'Studio asked Safaricom for your account balance using the operator you gave. The answer usually arrives within a minute. Keep this page open. On Test money, Safaricom accepting the request is enough to finish sign-up.',
      verifiedTitle: 'Your organisation is verified. Safaricom answered from your shortcode.',
      go: 'Go to Studio',
      failedTitle: 'Safaricom did not verify this organisation.',
      retry: 'Try again with a different password or credential',
      backToDaraja: 'Back to the Daraja app step',
    },
  },
  pageHeader: { safaricomPrefix: 'Safaricom calls this: ' },
  nav: Object.assign([
    { key: 'home', label: 'Home', safaricom: null, path: '/', icon: 'Home', phase: 1, available: true },
    { key: 'balances', label: 'Balances', safaricom: 'My Organization › Account', path: '/balances', icon: 'CreditCard', phase: 2, available: true },
    { key: 'send', label: 'Send money', safaricom: 'Initiate Transaction', path: '/send', icon: 'Send', phase: 2, available: true },
    { key: 'bulk', label: 'Bulk send', safaricom: 'Bulk Task › Bulk Payment', path: '/bulk', icon: 'Layers', phase: 5, available: false },
    { key: 'lookup', label: 'Look up a payment', safaricom: 'Transaction Status', path: '/lookup', icon: 'Search', phase: 2, available: true },
    { key: 'reverse', label: 'Reverse a payment', safaricom: 'Reversal', path: '/reverse', icon: 'RotateCcw', phase: 2, available: true },
    { key: 'money-in', label: 'Money in', safaricom: null, path: '/money-in', icon: 'Download', phase: 3, available: false },
    { key: 'stk', label: 'Ask a customer to pay', safaricom: 'STK Push', path: '/ask-to-pay', icon: 'Smartphone', phase: 3, available: true },
    { key: 'qr', label: 'QR codes', safaricom: 'Dynamic QR', path: '/qr', icon: 'Grid', phase: 4, available: true },
    { key: 'invoices', label: 'Invoices', safaricom: 'Bill Manager', path: '/invoices', icon: 'FileText', phase: 4, available: false },
    { key: 'standing-orders', label: 'Standing orders', safaricom: 'M-Pesa Ratiba', path: '/standing-orders', icon: 'Repeat', phase: 4, available: false },
    { key: 'express', label: 'Express checkout', safaricom: 'B2B Express Checkout', path: '/express', icon: 'Zap', phase: 4, available: false },
    { key: 'bonga', label: 'Bonga points', safaricom: 'Lipa na Bonga', path: '/bonga', icon: 'Star', phase: 3, available: false },
    { key: 'approvals', label: 'Waiting for approval', safaricom: 'Review Transaction', path: '/approvals', icon: 'CheckSquare', phase: 5, available: false },
    { key: 'history', label: 'History', safaricom: 'Account Statement', path: '/history', icon: 'Clock', phase: 2, available: true },
    { key: 'people', label: 'People', safaricom: 'Organization Operator', path: '/people', icon: 'Users', phase: 5, available: true },
    { key: 'settings', label: 'Settings', safaricom: 'My Preference', path: '/settings', icon: 'Settings', phase: 1, available: true },
    { key: 'not-possible', label: 'Not possible via API', safaricom: null, path: '/not-possible', icon: 'AlertCircle', phase: 1, available: true },
  ] as NavEntry[], { logout: 'Log out', menu: 'Menu' }),
  /** Hosted mode only, and only for a person the server says is a host admin (spec 6.1). */
  hostNavEntry: { key: 'host', label: 'Organisations', safaricom: null, path: '/host', icon: 'Server', phase: 3, available: true } as NavEntry,
  comingSoon: { title: 'Not in this version yet', badge: 'Coming soon', body: 'This feature is not available yet. Pages marked Coming soon are planned for a later release.' },
  login: { title: 'Log in', username: 'Username', password: 'Password', button: 'Log in', locked: 'Too many wrong tries. Wait 15 minutes and try again.', forgot: 'Forgotten your password?' },
  changePassword: {
    title: 'Choose your own password',
    intro: 'The password you were given is temporary. Choose a different one that only you know before using Studio.',
    current: 'Your temporary password',
    next: 'Your new password (at least 12 characters)',
    again: 'Type your new password again',
    save: 'Save my password',
  },
  recover: {
    title: 'Get back into your account',
    intro: "Prove this is your organisation. Type your M-Pesa shortcode, your API operator's name and its current password. Safaricom will answer within a minute and you can then choose a new Studio password.",
    username: 'Your username or e-mail address',
    shortcode: 'Your paybill or till number',
    operatorName: `Your API operator's name`,
    operatorPassword: `That operator's current password`,
    passwordNote: 'Studio sends this to Safaricom once to prove the organisation is yours. It is never stored.',
    start: 'Ask Safaricom',
    waitingTitle: 'Waiting for Safaricom',
    waiting: 'Studio asked Safaricom to answer for your shortcode. The answer usually arrives within a minute. Keep this page open.',
    newPassword: 'Choose a new password (at least 12 characters)',
    confirmPassword: 'Type the new password again',
    mismatch: 'The two passwords are not the same.',
    finish: 'Save the new password',
    doneTitle: 'Your password is changed. Every other device has been logged out.',
    goToLogin: 'Log in',
    tryAgain: 'Start again',
    alreadyUsed: 'This recovery has already been used. Start again if you still need a new password.',
  },
  people: {
    title: 'People',
    safaricom: 'Organization Operator',
    intro: 'Everybody who can log in to this organisation. Safaricom\'s own portal operators are separate; these are Studio accounts.',
    add: 'Add somebody',
    addTitle: 'Add somebody to this organisation',
    displayName: 'Their name',
    username: 'Their e-mail address',
    usernameSingle: 'A username for them',
    role: 'What may they do?',
    // The row selects get a name of their own: two controls labelled "What may they do?" on one
    // page (the add form and a row) would be ambiguous to a screen reader and to a test.
    roleFor: (name: string) => `What may ${name} do?`,
    roles: { owner: 'Owner — everything', operator: 'Operator — can send money', viewer: 'Viewer — can only look', custom: 'Custom — editing coming soon' } as Record<string, string>,
    temporaryPassword: 'A temporary password for them',
    regenerate: 'Suggest another',
    addButton: 'Add them',
    cancel: 'Cancel',
    tellThem: 'Tell them the temporary password yourself. They must change it the first time they log in.',
    shownOnce: 'This is the only time Studio shows it.',
    gotIt: 'Done',
    reset: 'New temporary password',
    suspend: 'Switch off',
    resume: 'Switch on',
    suspended: 'Switched off',
    mustChange: 'Must change their password',
    lastLogin: (when: string) => `Last logged in ${when}`,
    neverLoggedIn: 'Has not logged in yet',
    ownerNote: 'This is you. The owner cannot be changed here.',
    empty: 'Nobody else yet. Add a colleague and give them a role.',
    confirm: {
      add: (name: string) => `Add ${name} to this organisation?`,
      role: (name: string) => `Change what ${name} may do?`,
      reset: (name: string) => `Give ${name} a new temporary password?`,
      suspend: (name: string) => `Switch ${name} off?`,
      resume: (name: string) => `Switch ${name} back on?`,
    },
  },
  host: {
    title: 'Organisations',
    intro: 'Every organisation on this service: what state it is in with Safaricom, and how much it is using. You cannot see anybody\'s payments, settings or people.',
    filterStatus: 'Show',
    anyStatus: 'Any state',
    search: 'Search by name',
    searchButton: 'Search',
    loadMore: 'Show more',
    empty: 'No organisation matches that.',
    columns: { people: 'People', sends: 'Sends this month', lastCallback: 'Last answer from Safaricom', plan: 'Plan', periodEnd: 'Paid until' },
    noSubscription: 'No subscription',
    invoices: 'Invoices',
    noInvoices: 'No invoices yet.',
    invoiceStatus: { open: 'Due', paid: 'Paid', void: 'Cancelled' } as Record<string, string>,
    paymentStatus: { pending: 'Waiting on the phone', success: 'Paid', failed: 'Failed', timeout: 'No answer' } as Record<string, string>,
    exceptions: 'Payment exceptions',
    noExceptions: 'No payment exceptions need reconciling.',
    exceptionsLoading: 'Loading payment exceptions…',
    exceptionsLoadingMore: 'Loading…',
    exceptionsFailed: 'Could not load payment exceptions. The list below may be out of date.',
    exceptionsRetry: 'Try again',
    exceptionHint: 'A second success on a paid invoice, a contradictory amount, or an outcome Safaricom never answered. Read-only; no money is moved from here.',
    exceptionKind: { overpayment: 'Paid twice', amount_mismatch: 'Amount mismatch', unresolved: 'Outcome unknown' } as Record<string, string>,
    exceptionSuccesses: (count: number) => `${count} successful attempts on this invoice.`,
    exceptionAmounts: (expected: string, reported: string | null) => reported === null
      ? `Expected ${expected}; Safaricom's reported amount was not recorded.`
      : `Expected ${expected}; Safaricom reported ${reported}.`,
    plan: {
      title: 'Plan',
      instruct: 'Put this organisation on a plan now. A KES 1 test-plan invoice is issued at once, for the live payment check.',
      choose: 'Choose a plan',
      apply: 'Set this plan',
      done: (invoice: string) => `Plan set. Invoice ${invoice} is open.`,
      noInvoice: 'Plan set. An invoice is already open.',
    },
    billing: {
      title: 'Billing settings',
      intro: "Which of this service's own Daraja slots collects subscriptions, and the payee name shown on invoices. This is not the mode you work in.",
      env: 'Billing environment',
      notChosen: 'Not chosen yet',
      payeeName: 'Payee name',
      save: 'Save billing settings',
      saved: 'Billing settings saved.',
      slotReady: 'Ready: Safaricom has accepted the key and secret, and a passkey is saved.',
      slotMissing: (what: string) => `Not ready: ${what}.`,
      missingCreds: 'the shortcode, key and secret',
      missingVerified: 'Safaricom has not accepted the key and secret',
      missingPasskey: 'no passkey is saved',
    },
    stats: {
      title: 'This service right now',
      byStatus: 'Organisations',
      callbacks: 'Answers from Safaricom in the last hour',
      lapsing: 'Sign-ups the next sweep will close',
    },
    drawerTitle: 'Organisation',
    close: 'Close',
    slug: 'Handle',
    signedUp: 'Signed up',
    verifiedAt: 'Verified',
    peopleCount: 'People',
    sendsThisMonth: 'Sends this month',
    lastCallback: 'Last answer from Safaricom',
    never: 'Never',
    suspendReason: 'Why are you stopping this organisation?',
    suspend: 'Stop this organisation',
    resume: 'Start it again',
    suspended: 'Stopped.',
    resumed: 'Started again.',
    suspendNote: 'They keep every page they can read. Only sending and changing anything stops. Nothing is deleted.',
    admins: 'Who runs this service',
    adminsNote: 'Only people inside this organisation can run the service. At least one has to remain.',
    noAdmins: 'Nobody runs this service yet.',
    isAdmin: 'Runs this service',
    makeAdmin: 'Let them run this service',
    removeAdmin: 'Stop them running this service',
    confirm: {
      suspend: (name: string) => `Stop ${name}?`,
      resume: (name: string) => `Start ${name} again?`,
      admin: (name: string, on: boolean) => (on ? `Let ${name} run this service?` : `Stop ${name} running this service?`),
      plan: (name: string) => `Change ${name}'s plan now?`,
    },
  },
  confirm: { yourPassword: 'Your password', confirm: 'Confirm', cancel: 'Cancel', why: 'We ask for your password before anything that moves money or changes who can.' },
  error: { safaricomSaid: 'Safaricom said', meaning: 'What it means', whatToDo: 'What to do now', generic: 'Something went wrong on our side. Try again in a moment.', tryAgain: 'Try again in a moment. If it keeps happening, check Settings.' },
  home: {
    welcome: (name: string) => `Hello, ${name}.`,
    noOperator: 'You cannot send money yet. Add an API operator in Settings.',
    noPublicUrl: 'Safaricom cannot reach this studio yet. Test your public address in Settings.',
    stkOff: 'Ask a customer to pay is off. Add the STK passkey in Settings to turn it on.',
    connected: 'Everything is connected. Send money to a phone, check Balances, or look up a receipt.',
    latestBalance: 'Latest balance', noBalance: 'No balance yet', recent: 'Recent requests', noRecent: 'Nothing sent yet.',
    // Spec 7.4's banners.
    billingTrial: (date: string, kes: number) => `Free trial until ${date}. After that Studio costs KES ${kes} a month, paid by M-Pesa.`,
    billingDue: (kes: number, date: string) => `Your Studio payment of KES ${kes} is due by ${date}. Pay in Settings › Plan & billing to keep sending money.`,
    billingSuspended: 'Studio is read-only until the subscription is paid. Nothing has been deleted.',
  },
  request: {
    status: { pending: 'Preparing', sent: 'Sent, waiting for Safaricom', completed: 'Paid', failed: 'Failed', unknown: 'Unknown, needs a check', cancelled: 'Cancelled', rejected: 'Rejected', awaiting_approval: 'Waiting for approval' } as Record<string, string>,
    type: { b2c: 'Sent to a phone', stk: 'Asked a customer to pay', reversal: 'Reversal', balance: 'Balance check', status_query: 'Payment lookup' } as Record<string, string>,
    subtype: { BusinessPayment: 'Business payment', SalaryPayment: 'Salary', PromotionPayment: 'Promotion', refresh: 'Balance refresh', lookup: 'Lookup', sweep: 'Safaricom check' } as Record<string, string>,
    to: 'To', amount: 'Amount', receipt: 'Receipt', when: 'When', by: 'By',
    checkedBy: (name: string, note: string) => `Checked by ${name}: ${note}`,
    sendAgain: 'Send again', tryAgain: 'Try again', checkNow: 'Check with Safaricom now',
    checkSent: 'Check sent. The answer will show here within a few minutes.',
    markChecked: 'Mark as checked', markedChecked: 'Marked as checked.', markCheckedNote: 'What did you find? (for example: "Paid, seen in the portal")', markCheckedConfirm: 'Mark this as checked?',
    waiting: 'Waiting for Safaricom…', notFound: 'That request does not exist.', notFoundTitle: 'Request not found',
    timeline: { created: 'Created', sent: 'Sent', result: 'Result', checked: 'Checked' },
    source: { callback: "from Safaricom's reply", poll: 'from a status check', ack: "from Safaricom's acknowledgement" } as Record<string, string>,
  },
  send: {
    title: 'Send money', safaricom: 'Initiate Transaction', hubIntro: 'Choose where the money goes.', later: 'Coming soon',
    kinds: [
      { key: 'phone', label: 'To a phone', safaricom: 'Business Payment to Customer', path: '/send/phone', live: true },
      { key: 'pochi', label: 'To a business wallet (pochi)', safaricom: 'Business To Pochi', path: '/send/pochi', live: false },
      { key: 'paybill', label: 'To a paybill', safaricom: 'Business PayBill', path: '/send/paybill', live: false },
      { key: 'till', label: 'To a till', safaricom: 'Business Buy Goods', path: '/send/till', live: false },
      { key: 'float', label: 'Move float Working → Utility', safaricom: 'MMF to Utility', path: '/send/float', live: false },
      { key: 'topup', label: 'Top up another B2C shortcode', safaricom: 'B2C Account Top Up', path: '/send/topup', live: false },
      { key: 'kra', label: 'Pay tax to KRA', safaricom: 'Tax Remittance', path: '/send/kra', live: false },
    ],
    phone: {
      title: 'Send money to a phone', safaricom: 'Initiate Transaction › Business Payment to Customer',
      recipient: 'Phone number', amount: 'Amount (KES)', badPhone: 'Enter a Kenyan mobile number such as 0712 345 678.',
      wholeShillings: 'Whole shillings only. Safaricom does not send cents to phones.', centsNotAllowed: 'Remove the cents. Safaricom sends whole shillings to phones.',
      kind: 'What kind of payment is this?', kinds: { BusinessPayment: 'Business payment', SalaryPayment: 'Salary', PromotionPayment: 'Promotion' } as Record<string, string>,
      remarks: 'Note (optional, shows in History)', next: 'Review', back: 'Back', send: 'Send',
      againUnavailable: 'Studio could not load that earlier payment. Enter the details yourself.',
      review: {
        title: 'Check before you send', nameNote: 'Safaricom cannot check a phone name before sending. Check the number carefully.',
        feeNote: 'Safaricom charges its fee on top, taken from your Utility account.', debits: 'Taken from: Utility account',
        balanceNow: 'Utility balance now', balanceAfter: 'After this send', balanceMissing: 'No balance yet. Refresh in Balances to see it here.',
        balanceStale: (w: string) => `Balance last checked ${w}. Refresh in Balances if in doubt.`,
        short: 'Not enough in Utility for this send. Move float from Working first (arrives in 2B; use the Safaricom portal for now).',
        cap: (amount: string) => `This studio is capped at ${amount} per send.`,
      },
      confirmTitle: (amount: string, to: string) => `Send ${amount} to ${to}?`,
      duplicate: (w: string) => `You sent this already at ${w}. Send again?`, duplicateYes: 'Yes, send again', duplicateNo: 'No, cancel', duplicateCancelled: 'Cancelled.',
      result: { sent: 'Sent. Waiting for Safaricom…', completed: 'Paid.', failed: 'Not paid.', unknown: 'We do not know yet.', sendAnother: 'Send another' },
    },
  },
  askToPay: {
    title: 'Ask a customer to pay', safaricom: 'STK Push',
    intro: 'Safaricom shows the customer a prompt on their phone. They enter their M-Pesa PIN and the money arrives in your shortcode.',
    phone: 'Customer\u2019s phone number', amount: 'Amount (KES)',
    reference: 'What is this for?', referenceHint: 'Shown to the customer and on your statement, such as an invoice or order number.',
    description: 'Short description (optional)', descriptionHint: 'Up to 13 characters, shown on the prompt.',
    wholeShillings: 'Whole shillings only. Safaricom prompts for whole shillings.',
    next: 'Review', back: 'Back', ask: 'Ask for payment',
    review: {
      title: 'Check before you ask',
      note: 'The customer has about a minute to enter their PIN. Nothing is taken from your accounts.',
      incoming: 'Money comes in to your shortcode. This is not a send.',
    },
    duplicate: (w: string) => `You asked for this already at ${w}. Ask again?`,
    duplicateYes: 'Yes, ask again', duplicateNo: 'No, cancel', duplicateCancelled: 'Cancelled.',
    result: {
      sent: 'Asked. The prompt is on the customer\u2019s phone\u2026',
      completed: 'Paid.',
      failed: 'Not paid.',
      unknown: 'We do not know yet.',
      askAnother: 'Ask someone else',
    },
    waiting: 'Waiting for the customer. This page updates itself.',
  },
  balances: {
    title: 'Balances', safaricom: 'My Organization › Account',
    working: 'Working account', workingHint: 'Receives customer payments. Pays paybills and tills.',
    utility: 'Utility account', utilityHint: 'Pays phones. Fees come from here.', charges: 'Charges paid',
    asOf: (w: string) => `As of ${w}`, never: 'No balance yet.', refresh: 'Refresh', refreshing: 'Asking Safaricom…', refreshed: 'Balance updated.',
    stale: 'This is more than a day old. Refresh to be sure.', noAnswer: 'No answer within 5 minutes. Try Refresh again.', inFlight: 'A balance check is already on its way.',
  },
  lookup: {
    title: 'Look up a payment', safaricom: 'Transaction Status', receipt: 'M-Pesa receipt', hint: '10 letters and numbers, like RI6BZTPXNM',
    button: 'Look up', asking: 'Asking Safaricom…', says: 'Safaricom says', noAnswer: 'No answer within 5 minutes. Try again.',
    history: 'Looking for something sent from here? See History.',
    inFlight: 'Studio already asked Safaricom about this receipt. Wait for that answer.',
  },
  reverse: {
    title: 'Reverse a payment', safaricom: 'Reversal',
    receipt: 'M-Pesa receipt', hint: '10 letters and numbers, like RI6BZTPXNM',
    find: 'Find that payment', finding: 'Looking for that payment…',
    found: 'That payment settled here', settledOn: 'Settled', willTakeBack: 'Studio will ask Safaricom to take this back from the customer.',
    irreversible: 'A reversal cannot be undone. Check the receipt and the amount before you confirm.',
    spent: "Safaricom can only take the money back if the customer still has it. If they have spent it, the reversal will be refused, and Safaricom's own words will be shown here.",
    confirmTitle: (amount: string, receipt: string) => 'Reverse ' + amount + ' from ' + receipt + '?',
    button: 'Reverse', back: 'Back',
    result: { sent: 'Reversal sent. Waiting for Safaricom…', completed: 'Reversed.', failed: 'Not reversed.', unknown: 'We do not know yet. Studio will check.', another: 'Reverse another' },
    history: 'The reversal shows in History like any other request.',
  },
  history: {
    title: 'History', safaricom: 'Account Statement', search: 'Search phone, name or receipt', from: 'From', to: 'To', status: 'Status', any: 'Any status',
    empty: 'Nothing here yet. Send money to a phone and it will show up.', loadMore: 'Load more',
    columns: { when: 'When', what: 'What', to: 'To', amount: 'Amount', status: 'Status', receipt: 'Receipt' },
  },
  setup: {
    title: 'Set up your studio',
    steps: ['Owner', 'What you need', 'Environment', 'Your organization', 'Shortcode', 'Daraja app', 'Public address', 'STK passkey', 'API operator', 'Done'],
    owner: { displayName: 'Your name', username: 'Username', password: 'Choose a password (12+ characters)', button: 'Create owner' },
    /**
     * Asked in the business's own words, never in Safaricom's. Somebody setting up a shop should
     * not have to know what B2C or STK mean to answer correctly — the answers decide which steps
     * come next, so getting the wording right here is what keeps the rest of the wizard from
     * asking for things nobody needs.
     */
    uses: {
      title: 'What will you use M-Pesa for?',
      intro: 'Tick everything you need. You can change this later in Settings.',
      payOut: 'Pay money out to people',
      payOutHelp: 'Salaries, suppliers, refunds. Money leaves your account and arrives on a phone.',
      payOutSafaricom: 'Safaricom calls this B2C',
      collect: 'Ask customers to pay you on their phone',
      collectHelp: 'You enter their number and the amount. Their phone asks for their M-Pesa PIN.',
      collectSafaricom: 'Safaricom calls this M-Pesa Express, or STK Push',
      nothing: 'Choose at least one, so we know what to set up.',
    },
    org: { name: 'Business name', nominated: 'Nominated number (2547…)', notify: 'Notification phone (2547…)' },
    shortcode: { field: 'Paybill or till number', verified: (n: string) => `Safaricom knows this shortcode as "${n}".`, notVerified: 'Saved. We could not verify the name with Safaricom yet.' },
    env: {
      sandbox: 'Sandbox (test money, safe to try things)', sandboxHint: 'Use this to try the studio without moving real money.',
      production: 'Production (real money)', productionHint: 'Connects to your real M-Pesa account.',
      confirm: 'Type your shortcode to confirm production',
    },
    daraja: { key: 'Consumer key', secret: 'Consumer secret', where: 'From the Daraja portal › My Apps.', ok: 'Safaricom accepted the key and secret.' },
    /**
     * The step that proves a passkey, which nothing else can. No read-only Daraja call uses one,
     * so the only evidence it is right is Safaricom accepting a push made with it. A wrong one is
     * refused at the acknowledgement — before any phone rings — so this is safe: a failure costs
     * nothing and reaches nobody, and a success can be cancelled on the owner's own handset.
     */
    passkey: {
      field: 'STK passkey',
      where: 'From the Daraja portal, under Lipa Na M-Pesa Online for this shortcode.',
      phone: 'Your own phone number',
      phoneHelp: 'We send one test to this number. Use your own, not a customer’s.',
      testTitle: 'We will test it now',
      testBody: 'Your phone will ask for your M-Pesa PIN for KES 1. You can cancel it — we only need to see that Safaricom accepted it.',
      test: 'Save and test',
      testing: 'Asking Safaricom…',
      proven: 'Your passkey works. Safaricom accepted the request.',
      provenNote: 'If you cancelled the prompt, that is fine. Nothing was taken.',
      failedTitle: 'That passkey did not work.',
      failedBody: 'Safaricom refused it, so no prompt was sent to your phone and nothing was charged. Check you copied the passkey for this exact shortcode, then try again.',
      retry: 'Try another passkey',
    },
    operator: {
      name: 'Operator username (as in the Safaricom portal)',
      password: 'Operator password',
      cert: 'Safaricom certificate (paste the .cer text)',
      add: 'Add and test',
      skip: 'Skip for now',
      pending: 'Testing with a balance query…',
      verified: 'Verified. This operator can move money.',
      failed: 'Safaricom rejected this operator.',
      mode: 'How will you add this operator?',
      modePassword: 'I have the operator password and the Safaricom certificate',
      modeCredential: 'I already generated a Security Credential on the Daraja portal',
      credential: 'Security Credential (paste the whole value)',
      whereCredential: 'Daraja portal › Test Credentials › Generate Security Credential.',
    },
    publicUrl: { field: 'Your public address (https://…)', placeholder: 'https://pay.example.co.ke', test: 'Test my public address', ok: 'Safaricom will be able to reach you here.' },
    done: { title: 'All set', body: 'Your studio is ready. Start with Balances, or read what the API cannot do.', finish: 'Finish' },
    next: 'Next', back: 'Back',
  },
  settings: {
    title: 'Settings',
    organisation: {
      title: 'Organisation',
      nameNote: 'Change the name, nominated number and notification phone under "Your organization" below.',
      verification: 'What Safaricom has verified',
      verifiedWith: 'Safaricom has verified this organisation here.',
      notVerifiedWith: 'Not verified here yet.',
      creds: 'Daraja key and secret accepted',
      operator: 'A working API operator',
      shortcode: 'Shortcode',
      none: 'Not set',
      people: 'Who can log in',
      peopleLink: 'People',
    },
    billing: {
      title: 'Plan & billing',
      currentPlan: 'Your plan',
      price: (kes: number) => `KES ${kes} a month`,
      free: 'Free',
      trialUntil: (date: string) => `Free trial until ${date}`,
      runsUntil: (date: string) => `Runs until ${date}`,
      cancelledUntil: (date: string) => `Cancelled. Access continues until ${date}.`,
      pendingPlan: (name: string) => `${name} starts with the next invoice.`,
      usageTitle: 'What you are using',
      usagePeople: (used: number, max: number) => `People: ${used} of ${max}`,
      usagePeopleUnlimited: (used: number) => `People: ${used}`,
      usageSends: (used: number, max: number) => `Sends this month: ${used} of ${max}`,
      usageSendsUnlimited: (used: number) => `Sends this month: ${used}`,
      invoicesTitle: 'Invoices',
      noInvoices: 'No invoices yet.',
      status: { open: 'Due', paid: 'Paid', void: 'Cancelled' } as Record<string, string>,
      dueBy: (date: string) => `Due by ${date}`,
      paidOn: (date: string) => `Paid ${date}`,
      pay: 'Pay by M-Pesa',
      payTitle: (kes: number) => `Pay KES ${kes} by M-Pesa`,
      payPhone: 'Phone number to pay from',
      payHint: 'We will send an M-Pesa prompt to this phone. Enter your M-Pesa PIN on the phone to pay.',
      paySend: 'Send the prompt',
      waiting: 'Check your phone for the M-Pesa prompt…',
      check: 'Check now',
      checking: 'Checking…',
      checkAgainIn: (seconds: number) => `Check again in ${seconds}s`,
      issuedPlan: (name: string) => `Plan: ${name}`,
      payTo: (name: string) => `Payable to ${name}`,
      unresolvedHint: 'Safaricom may already have taken this payment. Do not send another prompt; the service owner has to reconcile it.',
      checkPrevious: 'Check the last request before paying again.',
      noSubscription: 'This organisation is not on a paid plan yet. The service owner sets the plan and issues its invoice.',
      hostExempt: 'The service owner runs Studio. This organisation is never billed.',
      paymentStatus: { pending: 'Waiting on the phone', success: 'Paid', failed: 'Failed', timeout: 'No answer', unresolved: 'Needs the service owner' } as Record<string, string>,
      receipt: (r: string) => `Receipt ${r}`,
      changePlan: 'Change plan',
      stayOn: (name: string) => `Stay on ${name}`,
      choose: 'Choose',
      current: 'Current plan',
      planChanged: (name: string) => `${name} starts with the next invoice.`,
      effectiveLimit: (name: string, what: string) => `${name} already limits ${what}. The plan itself starts with the next invoice.`,
      downgradeNow: 'Choosing a smaller plan limits new people and sends straight away; the plan itself starts with the next invoice.',
      overCapPeople: (limit: number, used: number) => `Your plan allows ${limit} ${limit === 1 ? 'person' : 'people'} and your organisation has ${used}. New people stay blocked until a larger plan's invoice is paid.`,
      overCapSends: "This month's sends are used. They resume next calendar month, or when a larger plan's invoice is paid.",
      recoveryDates: (from: string, due: string) => `A larger plan can be invoiced from ${from}; your next invoice is due by ${due}.`,
      cancel: 'Cancel subscription',
      cancelTitle: 'Cancel the subscription?',
      cancelled: 'Cancelled. Nothing was deleted.',
    },
    org: 'Your organization', daraja: 'Daraja app', passkey: 'STK passkey', publicUrl: 'Public address', operatorsTitle: 'API operators', allowlist: 'Safaricom callback addresses', advanced: 'Advanced',
    portalOnly: 'Change this in the Safaricom portal',
    orgPortalNote: (what: string) => `Contacts, KYC, bank account, tills: ${what}.`,
    publicUrlTested: (when: string) => `Tested ${when}`, publicUrlNotTested: 'Not tested yet',
    allowlistFieldLabel: 'Separate addresses with commas',
    hideSecret: 'Hide',
    operatorStatus: { pending: 'Testing', verified: 'Working', failed: 'Failed', disabled: 'Off' },
    rotate: 'New password', rotateCredential: 'New credential', rotateByCredential: 'Paste a new Security Credential', disable: 'Turn off', probe: 'Test again', add: 'Add another operator', expires: (d: string) => `Password expires ${d}`,
    newPasskey: 'New STK passkey',
    revealSecret: 'Show the callback secret', revealWhy: 'Only needed when debugging callbacks. It is part of the address Safaricom posts to, so treat it like a password and never share it.',
    save: 'Save', saved: 'Saved.', probeSent: 'Check sent. The result will show here within a few minutes.',
    darajaReplaceFailed: (message: string) => `${message} The new key and secret were not saved.`,
    mode: {
      title: 'Mode',
      sandbox: 'Sandbox — for testing, no real money',
      sandboxHint: 'Uses Safaricom’s sandbox. No real money moves.',
      production: 'Production — real money',
      productionHint: 'Your real Daraja app. Real M-Pesa money moves.',
      inUse: 'In use',
      confirmShortcode: 'Type your production shortcode to confirm',
      switched: (env: string) => `Now in ${env === 'production' ? 'Production' : 'Sandbox'} mode`,
      notReadyMissing: { creds: 'the Daraja key and secret', operator: 'an API operator' },
      notReady: (env: string, missing: string[]) => {
        const label = env === 'production' ? 'Production' : 'Sandbox';
        return `${label} is not ready: add ${missing.join(', and ')}, in the ${label} tab.`;
      },
    },
    tabs: { sandbox: 'Sandbox', production: 'Production' },
    secret: {
      saved: 'Saved', savedEndsIn: (last4: string) => `Saved, ends in ${last4}`, verifiedAt: (when: string) => `Accepted by Safaricom ${when}`, notSet: 'Not set', replaced: 'Replaced.',
      notYetAccepted: 'Saved, not yet accepted by Safaricom — test the key and secret.',
    },
    cert: { label: 'Certificate', hint: 'Used when adding an API operator by password (not needed for a Security Credential).' },
    operators: { switchToTest: (env: string) => `Switch to ${env === 'production' ? 'Production' : 'Sandbox'} mode to test this operator.` },
    shortcode: {
      label: 'Paybill or till number',
      knownAs: (name: string) => `Saved. Safaricom knows this shortcode as ${name}.`,
      unverified: 'Saved. Not yet verified with Safaricom.',
    },
    b2cApi: {
      title: 'B2C API version',
      auto: 'Automatic (recommended)',
      autoHint: 'Studio finds out which version your app can use on the first send and keeps using it. If Safaricom later enables v3 for your app, choose v3 here.',
      v1: 'v1', v1Hint: 'Works with every Daraja app that has B2C.',
      v3: 'v3', v3Hint: 'Only if Safaricom enabled B2C v3 for your app.',
      detected: (version: string, when: string) => `Detected: ${version} (found ${when})`,
      saved: 'B2C API version saved.',
    },
    confirm: {
      org: 'Save the organisation details?',
      publicUrl: 'Save the public address?',
      switchMode: (env: string) => `Switch to ${env === 'production' ? 'Production' : 'Sandbox'}?`,
      saveShortcode: 'Save the shortcode?',
      replaceCreds: 'Replace the Daraja key and secret?',
      replacePasskey: 'Replace the STK passkey?',
      saveB2cApi: 'Save the B2C API version?',
      rotate: (name: string) => `Use a new password for ${name}?`,
      disable: (name: string) => `Turn off ${name}?`,
      add: (name: string) => `Add operator ${name}?`,
      allowlist: 'Change the Safaricom address list?',
      reveal: 'Show the callback secret?',
    },
  },
  toast: { close: 'Dismiss' },
  notPossiblePage: {
    title: 'Not possible via API',
    intro: 'Safaricom keeps these in its portal. Each card says why, and exactly where to go.',
    why: 'Why not here:',
    where: 'Where:',
    phone: 'Phone:',
    portalLink: 'Open the Safaricom portal',
  },
  notPossible: [
    { key: 'bank-withdrawal', title: 'Withdraw to the bank', what: 'Move money from M-Pesa to your bank account (normal or real-time).', why: 'Safaricom offers no API for organization withdrawals. Only the portal and USSD can start one.', portalPath: 'Transaction › Initiate Transaction › Organization Withdrawal From M-PESA', ussd: '*234*4#' },
    { key: 'utility-to-working', title: 'Move float from Utility to Working', what: 'Sweep collections from the Utility account into the Working (MMF) account.', why: 'The API command for this direction always fails with ResultCode 21. Safaricom API support confirmed it is manual only.', portalPath: 'Transaction › Initiate Transaction › Pay Bill Services – MMF Account Transfer', ussd: '*234# (full sweep)' },
    { key: 'operators', title: 'Create operators and give them roles', what: 'Add a person or API user in the Safaricom portal, set their access channel and roles.', why: 'Operator management has no API. Studio permissions sit on top of Safaricom roles; both must exist.', portalPath: 'Search › Organization Operator › Create, or › Detail › Role › Edit' },
    { key: 'operator-password', title: "Reset an operator's portal password", what: 'Send a new password to a portal operator.', why: 'No API. Studio can only take a new API password after you set it in the portal.', portalPath: 'Search › Organization Operator › Detail › Reset Password' },
    { key: 'org-profile', title: 'Organization profile and KYC', what: 'Contacts, nominated number, notification phone, Double Hakikisha, Reversal Initiation.', why: 'KYC data is portal-only. Studio keeps a read-only copy you type in once.', portalPath: 'Search › Organization › Details › KYC Info › Edit' },
    { key: 'bank-accounts', title: 'Bank accounts', what: 'Add, edit or remove the bank account linked to the shortcode.', why: 'No API.', portalPath: 'Search › My Organization › Bank Account' },
    { key: 'tills', title: 'Tills', what: 'Create or close a till under the organization.', why: 'No API.', portalPath: 'Search › My Organization › Till' },
    { key: 'revenue-settlement', title: 'Revenue settlement plans', what: 'Schedule settlements to the bank.', why: 'No API.', portalPath: 'Business Center › Revenue Settlement' },
    { key: 'tax-exemption', title: 'Tax exemption, accounting model, state tags', what: 'Organization-level tax and hierarchy settings.', why: 'No API.', portalPath: 'Search › Organization › Details' },
    { key: 'close-org', title: 'Close the organization', what: 'Permanently close the shortcode.', why: 'No API, by design.', portalPath: 'Search › Organization › Close' },
    { key: 'statement', title: "Safaricom's own account statement", what: 'The official statement with running balance per account.', why: 'No statement API. Studio History is its own ledger built from callbacks and pulls, not Safaricom’s statement.', portalPath: 'Transaction › Account Statement › Export' },
    { key: 'bulk-operators', title: 'Bulk operator creation', what: 'Upload a CSV of operators.', why: 'No API.', portalPath: 'Business Center › Bulk Task › Create Organization Operator' },
    { key: 'approval-switch', title: 'Operator Creation Approval Switch', what: "Portal's own maker-checker for creating operators.", why: 'Portal setting only.', portalPath: 'Search › Organization › Details › KYC Info' },
    { key: 'c2b-urls', title: 'Change registered paybill callback URLs', what: 'Point paybill payments at a different system after the first registration in production.', why: 'Production Daraja refuses to overwrite registered URLs. Delete and re-add them in the Daraja portal.', portalPath: 'Daraja portal › My Apps › your app › C2B URLs' },
    { key: 'portal-audit', title: 'Audit log of portal actions', what: 'What people did inside the Safaricom portal.', why: 'No API. Studio audits only what happens in studio.', portalPath: 'My Preference › Audit Log' },
  ] as NotPossibleItem[],
};
