import type { IconName } from '../icons/lineMd';

export interface NavEntry { key: string; label: string; safaricom: string | null; path: string; icon: IconName; group: 'home' | 'money' | 'manage' | 'help'; phase: 1 | 2 | 3 | 4 | 5; available: boolean }
export interface NotPossibleItem { key: string; title: string; what: string; why: string; portalPath: string; ussd?: string }

export const copy = {
  qr: {
    title: 'QR codes', safaricom: 'Dynamic QR',
    payee: 'Paid to', shortcode: 'Shortcode', reference: 'Payment reference', referenceHint: 'An order or account reference, up to 32 characters.',
    type: 'How customers pay', paybill: 'Pay Bill', till: 'Buy Goods (till)',
    amount: 'Amount (KES)', customerAmount: 'Customer enters the amount', who: 'Who sets the amount?', fixed: 'A fixed amount',
    generate: 'Create QR code', generating: 'Creating the code…', download: 'Download QR image',
    imageAlt: 'M-Pesa payment QR code', ready: 'QR code ready',
    scan: 'The customer scans this with their M-Pesa app and checks the payee before paying.',
    unpaid: 'A scan does not confirm payment. Check your M-Pesa confirmation.',
    sandbox: 'Test money — this code cannot collect real money.', production: 'Real money — a scan pays you.',
    noPermission: 'You need permission to create QR codes. Ask the owner.',
    noResponse: 'No usable response was received.', retry: 'Check your settings and connection, then try again.',
    badResponse: 'Studio could not display the QR image. Create a new code.',
  },
  appName: 'Daraja Studio',
  app: {
    loading: 'Loading…',
    errorTitle: 'Cannot reach the studio server.',
    errorBody: 'Check that the server is running, then try again.',
    retry: 'Try again',
    navLabel: 'Main',
  },
  org: {
    name: 'Organisation',
    // Plain English in the pill; Safaricom's own word sits under it in grey.
    badge: { sandbox: 'Test money', production: 'Real money' } as Record<string, string>,
    badgeSafaricom: { sandbox: 'Sandbox', production: 'Production' } as Record<string, string>,
    envLine: { sandbox: 'Test money · Sandbox', production: 'Real money · Production' } as Record<string, string>,
    suspended: 'This organisation is read-only. Nothing has been deleted.',
    signedUp: 'Signed up',
    verifiedOn: 'Verified by Safaricom',
    status: {
      pending: 'Signing up', creds_ok: 'Signing up', operator_probing: 'Waiting for Safaricom',
      failed: 'Sign-up did not finish', verified: 'Verified', suspended: 'Read-only', closed: 'Closed',
    } as Record<string, string>,
  },
  pageHeader: { safaricomPrefix: 'Safaricom calls this: ' },
  nav: Object.assign([
    { key: 'home', label: 'Home', safaricom: null, path: '/', icon: 'home', group: 'home', phase: 1, available: true },
    { key: 'send', label: 'Send money', safaricom: 'Initiate Transaction', path: '/send', icon: 'arrow-right-circle', group: 'money', phase: 2, available: true },
    { key: 'bulk', label: 'Bulk send', safaricom: 'Bulk Task › Bulk Payment', path: '/bulk', icon: 'document-list', group: 'money', phase: 5, available: false },
    { key: 'reverse', label: 'Reverse a payment', safaricom: 'Reversal', path: '/reverse', icon: 'arrow-left-circle', group: 'money', phase: 2, available: true },
    { key: 'money-in', label: 'Money in', safaricom: null, path: '/money-in', icon: 'arrow-down-circle', group: 'money', phase: 3, available: false },
    { key: 'stk', label: 'Ask a customer to pay', safaricom: 'STK Push', path: '/ask-to-pay', icon: 'cellphone', group: 'money', phase: 3, available: true },
    { key: 'qr', label: 'QR codes', safaricom: 'Dynamic QR', path: '/qr', icon: 'grid-3', group: 'money', phase: 4, available: true },
    { key: 'invoices', label: 'Invoices', safaricom: 'Bill Manager', path: '/invoices', icon: 'file-document', group: 'money', phase: 4, available: false },
    { key: 'standing-orders', label: 'Standing orders', safaricom: 'M-Pesa Ratiba', path: '/standing-orders', icon: 'calendar', group: 'money', phase: 4, available: false },
    { key: 'express', label: 'Express checkout', safaricom: 'B2B Express Checkout', path: '/express', icon: 'speed', group: 'money', phase: 4, available: false },
    { key: 'bonga', label: 'Bonga points', safaricom: 'Lipa na Bonga', path: '/bonga', icon: 'star', group: 'money', phase: 3, available: false },
    { key: 'approvals', label: 'Waiting for approval', safaricom: 'Review Transaction', path: '/approvals', icon: 'clipboard-check', group: 'money', phase: 5, available: false },
    { key: 'history', label: 'History', safaricom: 'Account Statement', path: '/history', icon: 'list', group: 'money', phase: 2, available: true },
    { key: 'people', label: 'People', safaricom: 'Organization Operator', path: '/people', icon: 'account', group: 'manage', phase: 5, available: true },
    { key: 'settings', label: 'Settings', safaricom: 'My Preference', path: '/settings', icon: 'cog', group: 'manage', phase: 1, available: true },
    { key: 'not-possible', label: 'Not possible via API', safaricom: null, path: '/not-possible', icon: 'alert-circle', group: 'help', phase: 1, available: true },
  ] as NavEntry[], { logout: 'Log out', menu: 'Menu', groups: { money: 'Money', manage: 'Manage' }, planned: (n: number) => `${n} planned features` }),
  comingSoon: { title: 'Not in this version yet', badge: 'Coming soon', body: 'Planned for a later release.' },
  login: { title: 'Log in', username: 'Username', password: 'Password', button: 'Log in', locked: 'Too many wrong tries. Wait 15 minutes and try again.' },
  changePassword: {
    title: 'Choose your own password',
    intro: 'Your password is temporary. Choose your own before using Studio.',
    current: 'Your temporary password',
    next: 'Your new password (at least 12 characters)',
    again: 'Type your new password again',
    save: 'Save my password',
    voluntaryIntro: 'Choose a new password.',
    mismatch: 'The two passwords are not the same.',
    cancel: 'Cancel',
  },
  people: {
    title: 'People',
    safaricom: 'Organization Operator',
    add: 'Add somebody',
    addTitle: 'Add somebody to this organisation',
    displayName: 'Their name',
    usernameSingle: 'A username for them',
    role: 'What may they do?',
    roleShort: { operator: 'Operator', viewer: 'Viewer' } as Record<string, string>,
    // The row selects get a name of their own: two controls labelled "What may they do?" on one
    // page (the add form and a row) would be ambiguous to a screen reader and to a test.
    roleFor: (name: string) => `What may ${name} do?`,
    roles: { owner: 'Owner — everything', operator: 'Operator — can send money', viewer: 'Viewer — can only look', custom: 'Custom — editing coming soon' } as Record<string, string>,
    temporaryPassword: 'A temporary password for them',
    regenerate: 'Suggest another',
    addButton: 'Add them',
    cancel: 'Cancel',
    tellThem: 'Tell them this password yourself. They must change it at first login.',
    shownOnce: 'This is the only time Studio shows it.',
    gotIt: 'Done',
    reset: 'New temporary password',
    suspend: 'Switch off',
    resume: 'Switch on',
    suspended: 'Switched off',
    mustChange: 'Must change their password',
    lastLogin: (when: string) => `Last logged in ${when}`,
    neverLoggedIn: 'Has not logged in yet',
    ownerNote: 'This is you.',
    empty: 'Nobody else yet.',
    confirm: {
      add: (name: string) => `Add ${name} to this organisation?`,
      role: (name: string) => `Change what ${name} may do?`,
      reset: (name: string) => `Give ${name} a new temporary password?`,
      suspend: (name: string) => `Switch ${name} off?`,
      resume: (name: string) => `Switch ${name} back on?`,
    },
  },
  confirm: { yourPassword: 'Your password', confirm: 'Confirm', cancel: 'Cancel', why: 'Your password is needed for anything that moves money or changes who can.' },
  error: { safaricomSaid: 'Safaricom said', meaning: 'What it means', whatToDo: 'What to do now', generic: 'Something went wrong on our side. Try again in a moment.', tryAgain: 'Try again in a moment. If it keeps happening, check Settings.' },
  home: {
    finishSetup: 'Finish setting up',
    noOperator: 'You cannot send money yet. Add an API operator in Settings.',
    noPublicUrl: 'Safaricom cannot reach this studio yet. Test your public address in Settings.',
    stkOff: 'Ask a customer to pay is off. Add the STK passkey in Settings to turn it on.',
    connected: 'Connected to Safaricom.', viewAll: 'View all',
    latestBalance: 'Latest balance', noBalance: 'No balance yet', recent: 'Recent requests', noRecent: 'Nothing sent yet.',
  },
  request: {
    status: { pending: 'Preparing', sent: 'Waiting', completed: 'Paid', failed: 'Failed', unknown: 'Needs a check', cancelled: 'Cancelled', rejected: 'Rejected', awaiting_approval: 'Waiting for approval' } as Record<string, string>,
    type: { b2c: 'Sent to a phone', stk: 'Asked a customer to pay', reversal: 'Reversal', balance: 'Balance check', status_query: 'Payment lookup' } as Record<string, string>,
    subtype: { BusinessPayment: 'Business payment', SalaryPayment: 'Salary', PromotionPayment: 'Promotion', refresh: 'Balance refresh', lookup: 'Lookup', sweep: 'Safaricom check' } as Record<string, string>,
    to: 'To', amount: 'Amount', receipt: 'Receipt', when: 'When', by: 'By', category: 'Category',
    checkedBy: (name: string, note: string) => `Checked by ${name}: ${note}`,
    sendAgain: 'Send again', tryAgain: 'Try again', checkNow: 'Check with Safaricom now', reverseThis: 'Reverse this payment',
    checkSent: 'Check sent. The answer will show here within a few minutes.',
    markChecked: 'Mark as checked', markedChecked: 'Marked as checked.', markCheckedNote: 'What did you find? (for example: "Paid, seen in the portal")', markCheckedConfirm: 'Mark this as checked?',
    waiting: 'Waiting for Safaricom…', notFound: 'That request does not exist.', notFoundTitle: 'Request not found',
    timeline: { created: 'Created', sent: 'Sent', result: 'Result', checked: 'Checked' },
    source: { callback: "from Safaricom's reply", poll: 'from a status check', ack: "from Safaricom's acknowledgement" } as Record<string, string>,
  },
  send: {
    title: 'Send money', safaricom: 'Initiate Transaction', later: 'Coming soon', planned: 'Planned', phoneIntro: 'Money leaves your Utility account and arrives on the phone.',
    kinds: [
      { key: 'phone', label: 'To a phone', safaricom: 'Business Payment to Customer', path: '/send/phone', live: true },
      { key: 'pochi', label: 'To a business wallet (pochi)', safaricom: 'Business To Pochi', path: '/send/pochi', live: false },
      { key: 'paybill', label: 'To a paybill', safaricom: 'Business PayBill', path: '/send/paybill', live: false },
      { key: 'till', label: 'To a till', safaricom: 'Business Buy Goods', path: '/send/till', live: false },
      { key: 'float', label: 'Move float Working → Utility', safaricom: 'MMF to Utility', path: '/send/float', live: false },
      { key: 'topup', label: 'Top up another B2C shortcode', safaricom: 'B2C Account Top Up', path: '/send/topup', live: false },
      { key: 'kra', label: 'Pay tax to KRA', safaricom: 'Tax Remittance', path: '/send/kra', live: false },
    ],
    phone: {
      title: 'Send money to a phone', safaricom: 'Initiate Transaction › Business Payment to Customer',
      recipient: 'Phone number', amount: 'Amount (KES)', badPhone: 'Enter a Kenyan mobile number such as 0712 345 678.',
      wholeShillings: 'Whole shillings only. Safaricom does not send cents to phones.', centsNotAllowed: 'Remove the cents. Safaricom sends whole shillings to phones.',
      kind: 'What kind of payment is this?', kinds: { BusinessPayment: 'Business payment', SalaryPayment: 'Salary', PromotionPayment: 'Promotion' } as Record<string, string>,
      remarks: 'Note (optional)', next: 'Review', back: 'Back', send: 'Send', kindManage: 'Manage',
      againUnavailable: 'Studio could not load that earlier payment. Enter the details yourself.',
      review: {
        title: 'Check before you send', nameNote: 'Safaricom cannot check the name before sending. Check the number.',
        feeNote: 'Safaricom charges its fee on top, taken from your Utility account.', debits: 'Taken from: Utility account',
        balanceNow: 'Utility balance now', balanceAfter: 'After this send', balanceMissing: 'No balance yet. Refresh in Balances to see it here.',
        balanceStale: (w: string) => `Balance last checked ${w}. Refresh in Balances if in doubt.`,
        short: 'Not enough in Utility for this send. Move float from Working first (arrives in 2B; use the Safaricom portal for now).',
        cap: (amount: string) => `This studio is capped at ${amount} per send.`,
      },
      confirmTitle: (amount: string, to: string) => `Send ${amount} to ${to}?`,
      duplicate: (w: string) => `You sent this already at ${w}. Send again?`, duplicateYes: 'Yes, send again', duplicateNo: 'No, cancel', duplicateCancelled: 'Cancelled.',
      result: { sent: 'Sent. Waiting for Safaricom…', completed: 'Paid.', failed: 'Not paid.', unknown: 'We do not know yet.', sendAnother: 'Send another' },
    },
  },
  askToPay: {
    title: 'Ask a customer to pay', safaricom: 'STK Push',
    intro: 'The customer gets a prompt on their phone and enters their M-Pesa PIN.',
    phone: 'Customer\u2019s phone number', amount: 'Amount (KES)',
    reference: 'What is this for?', referenceHint: 'An invoice or order number. Shown to the customer and on your statement.',
    description: 'Short description (optional)', descriptionHint: 'Up to 13 characters, shown on the prompt.',
    wholeShillings: 'Whole shillings only. Safaricom prompts for whole shillings.',
    next: 'Review', back: 'Back', ask: 'Ask for payment',
    review: {
      title: 'Check before you ask',
      note: 'The customer has about a minute to enter their PIN. Nothing leaves your accounts.',
    },
    duplicate: (w: string) => `You asked for this already at ${w}. Ask again?`,
    duplicateYes: 'Yes, ask again', duplicateNo: 'No, cancel', duplicateCancelled: 'Cancelled.',
    result: {
      sent: 'Asked. The prompt is on the customer\u2019s phone\u2026',
      completed: 'Paid.',
      failed: 'Not paid.',
      unknown: 'We do not know yet.',
      askAnother: 'Ask someone else',
    },
    waiting: 'Waiting for the customer.',
  },
  balances: {
    title: 'Balances', safaricom: 'My Organization › Account',
    working: 'Working account', workingHint: 'Customer payments in. Pays paybills and tills.',
    utility: 'Utility account', utilityHint: 'Pays phones. Fees come from here.', charges: 'Charges paid',
    asOf: (w: string) => `As of ${w}`, never: 'No balance yet.', refresh: 'Refresh', refreshing: 'Asking Safaricom…', refreshed: 'Balance updated.',
    stale: 'This is more than a day old. Refresh to be sure.', noAnswer: 'No answer within 5 minutes. Try Refresh again.', inFlight: 'A balance check is already on its way.',
  },
  lookup: {
    title: 'Look up a payment', safaricom: 'Transaction Status', receipt: 'M-Pesa receipt', hint: '10 letters and numbers, like RI6BZTPXNM',
    button: 'Look up', asking: 'Asking Safaricom…', says: 'Safaricom says', noAnswer: 'No answer within 5 minutes. Try again.',
    history: 'Sent from here? See History.',
    notHere: 'This receipt was not sent from here.', ask: 'Ask Safaricom about this receipt',
    inFlight: 'Studio already asked Safaricom about this receipt. Wait for that answer.',
  },
  reverse: {
    title: 'Reverse a payment', safaricom: 'Reversal',
    receipt: 'M-Pesa receipt', hint: '10 letters and numbers, like RI6BZTPXNM',
    find: 'Find that payment', finding: 'Looking for that payment…',
    found: 'That payment settled here', settledOn: 'Settled', willTakeBack: 'Studio will ask Safaricom to take this back from the customer.',
    irreversible: 'A reversal cannot be undone. Check the receipt and the amount before you confirm.',
    spent: 'Safaricom can only take back money the customer still has. If it is spent, the reversal is refused.',
    confirmTitle: (amount: string, receipt: string) => 'Reverse ' + amount + ' from ' + receipt + '?',
    button: 'Reverse', back: 'Back',
    result: { sent: 'Reversal sent. Waiting for Safaricom…', completed: 'Reversed.', failed: 'Not reversed.', unknown: 'We do not know yet. Studio will check.', another: 'Reverse another' },
    history: 'The reversal shows in History.',
  },
  history: {
    title: 'History', safaricom: 'Account Statement', search: 'Search phone, name or receipt', searchPlaceholder: 'Phone, name or receipt', from: 'From', to: 'To', status: 'Status', any: 'Any status',
    empty: 'Nothing here yet.', loadMore: 'Load more', previous: 'Previous', next: 'Next', page: (n: number) => `Page ${n}`,
    columns: { when: 'When', what: 'What', to: 'To', amount: 'Amount', status: 'Status', receipt: 'Receipt' },
  },
  setup: {
    title: 'Set up your studio',
    steps: ['Owner', 'What you need', 'Environment', 'Your organization', 'Shortcode', 'Daraja app', 'Public address', 'STK passkey', 'API operator', 'Done'],
    stepOf: (n: number, of: number) => `Step ${n} of ${of}`,
    /** One plain sentence per step: what it is for and where the value comes from. */
    intro: {
      owner: 'Your own login. Nobody else sees this password.',
      uses: 'Tick everything you need. You can change this later in Settings.',
      environment: 'Sandbox uses pretend money. Production is your real M-Pesa account.',
      org: 'Shown in the menu and on receipts.',
      shortcode: 'Your paybill or till number, as on your Safaricom letter.',
      daraja: 'From developer.safaricom.co.ke, under My Apps.',
      'public-url': 'Safaricom sends payment results here. It must be reachable from the internet.',
      passkey: 'From the Daraja portal, under Lipa Na M-Pesa Online. Tested right away.',
      operator: 'The Safaricom portal user allowed to move money out of your account.',
      done: 'Everything Safaricom needs is in place.',
    } as Record<string, string>,
    owner: { displayName: 'Your name', username: 'Username', password: 'Choose a password (12+ characters)', button: 'Create owner' },
    /**
     * Asked in the business's own words, never in Safaricom's. Somebody setting up a shop should
     * not have to know what B2C or STK mean to answer correctly — the answers decide which steps
     * come next, so getting the wording right here is what keeps the rest of the wizard from
     * asking for things nobody needs.
     */
    uses: {
      title: 'What will you use M-Pesa for?',
      payOut: 'Pay money out to people',
      payOutHelp: 'Salaries, suppliers, refunds. Money leaves your account and arrives on a phone.',
      payOutSafaricom: 'Safaricom calls this B2C',
      collect: 'Ask customers to pay you on their phone',
      collectHelp: 'You enter their number and the amount. Their phone asks for their M-Pesa PIN.',
      collectSafaricom: 'Safaricom calls this M-Pesa Express, or STK Push',
      nothing: 'Choose at least one, so we know what to set up.',
    },
    org: { name: 'Business name', nominated: 'Nominated number (2547…)', notify: 'Notification phone (2547…)' },
    shortcode: { field: 'Paybill or till number', verified: (n: string) => `Safaricom knows this shortcode as "${n}".`, notVerified: 'Saved. We could not verify the name with Safaricom yet.' },
    env: {
      sandbox: 'Sandbox (test money, safe to try things)', sandboxHint: 'Use this to try the studio without moving real money.',
      production: 'Production (real money)', productionHint: 'Connects to your real M-Pesa account.',
      confirm: 'Type your shortcode to confirm production',
    },
    daraja: { key: 'Consumer key', secret: 'Consumer secret', where: 'From the Daraja portal › My Apps.', ok: 'Safaricom accepted the key and secret.' },
    /**
     * The step that proves a passkey, which nothing else can. No read-only Daraja call uses one,
     * so the only evidence it is right is Safaricom accepting a push made with it. A wrong one is
     * refused at the acknowledgement — before any phone rings — so this is safe: a failure costs
     * nothing and reaches nobody, and a success can be cancelled on the owner's own handset.
     */
    passkey: {
      field: 'STK passkey',
      where: 'From the Daraja portal, under Lipa Na M-Pesa Online for this shortcode.',
      phone: 'Your own phone number',
      phoneHelp: 'We send one test to this number. Use your own, not a customer’s.',
      testTitle: 'We will test it now',
      testBody: 'Your phone will ask for your M-Pesa PIN for KES 1. You can cancel it — we only need to see that Safaricom accepted it.',
      test: 'Save and test',
      testing: 'Asking Safaricom…',
      proven: 'Your passkey works. Safaricom accepted the request.',
      provenNote: 'If you cancelled the prompt, that is fine. Nothing was taken.',
      failedTitle: 'That passkey did not work.',
      failedBody: 'Safaricom refused it, so no prompt was sent to your phone and nothing was charged. Check you copied the passkey for this exact shortcode, then try again.',
      retry: 'Try another passkey',
    },
    operator: {
      name: 'Operator username (as in the Safaricom portal)',
      password: 'Operator password',
      cert: 'Safaricom certificate (paste the .cer text)',
      add: 'Add and test',
      skip: 'Skip for now',
      pending: 'Testing with a balance query…',
      verified: 'Verified. This operator can move money.',
      failed: 'Safaricom rejected this operator.',
      mode: 'How will you add this operator?',
      modePassword: 'I have the operator password and the Safaricom certificate',
      modeCredential: 'I already generated a Security Credential on the Daraja portal',
      credential: 'Security Credential (paste the whole value)',
      whereCredential: 'Daraja portal › Test Credentials › Generate Security Credential.',
    },
    publicUrl: { field: 'Your public address (https://…)', placeholder: 'https://pay.example.co.ke', test: 'Test my public address', ok: 'Safaricom will be able to reach you here.' },
    done: { title: 'All set', body: 'Your studio is ready.', finish: 'Finish' },
    next: 'Next', back: 'Back',
  },
  settings: {
    title: 'Settings',
    organisation: {
      title: 'Organisation',
      verification: 'Safaricom verification',
      verifiedWith: 'Verified',
      notVerifiedWith: 'Not verified',
      creds: 'Daraja key and secret accepted',
      operator: 'A working API operator',
      shortcode: 'Shortcode',
      none: 'Not set',
      people: 'Who can log in',
      peopleLink: 'Manage people',
      callbackSecret: 'Callback secret',
    },
    org: 'Your organization', daraja: 'Daraja app', passkey: 'STK passkey', publicUrl: 'Public address', operatorsTitle: 'API operators', allowlist: 'Safaricom callback addresses', advanced: 'Advanced',
    change: 'Change', replace: 'Replace', test: 'Test', addOperator: 'Add operator', hidden: 'Hidden',
    appearance: { title: 'Appearance', system: 'System', light: 'Light', dark: 'Dark' },
    envSettings: (env: string) => `${env === 'production' ? 'Production' : 'Sandbox'} settings`,
    categories: {
      title: 'Payment categories', intro: 'Your own names for a send. Each one goes to Safaricom as one of its three kinds.',
      add: 'Add category', name: 'Category name', kind: 'Sent to Safaricom as', edit: 'Edit', remove: 'Delete', last: 'Keep at least one category.', saved: 'Categories saved.',
      confirm: 'Save the payment categories?',
    },
    portalOnly: 'Change this in the Safaricom portal',
    orgPortalNote: (what: string) => `Contacts, KYC, bank account, tills: ${what}.`,
    publicUrlTested: (when: string) => `Tested ${when}`, publicUrlNotTested: 'Not tested yet',
    allowlistFieldLabel: 'Separate addresses with commas',
    hideSecret: 'Hide',
    nominated: 'Nominated number', notify: 'Notification phone',
    operatorStatus: { pending: 'Testing', verified: 'Working', failed: 'Failed', disabled: 'Off' },
    rotate: 'New password', rotateCredential: 'New credential', rotateByCredential: 'Paste a new Security Credential', disable: 'Turn off', probe: 'Test again', add: 'Add another operator', expires: (d: string) => `Password expires ${d}`,
    newPasskey: 'New STK passkey',
    revealSecret: 'Show the callback secret', revealWhy: 'Part of the address Safaricom posts to. Treat it like a password.',
    save: 'Save', saved: 'Saved.', probeSent: 'Check sent. The result will show here within a few minutes.',
    darajaReplaceFailed: (message: string) => `${message} The new key and secret were not saved.`,
    mode: {
      title: 'Mode',
      sandbox: 'Sandbox — for testing, no real money',
      sandboxHint: 'Uses Safaricom’s sandbox. No real money moves.',
      production: 'Production — real money',
      productionHint: 'Your real Daraja app. Real M-Pesa money moves.',
      inUse: 'In use',
      confirmShortcode: 'Type your production shortcode to confirm',
      switched: (env: string) => `Now in ${env === 'production' ? 'Production' : 'Sandbox'} mode`,
      notReadyMissing: { creds: 'the Daraja key and secret', operator: 'an API operator' },
      notReady: (env: string, missing: string[]) => {
        const label = env === 'production' ? 'Production' : 'Sandbox';
        return `${label} is not ready: add ${missing.join(', and ')}, below.`;
      },
    },
    tabs: { sandbox: 'Sandbox', production: 'Production' },
    secret: {
      saved: 'Saved', savedEndsIn: (last4: string) => `Saved, ends in ${last4}`, verifiedAt: (when: string) => `Accepted by Safaricom ${when}`, notSet: 'Not set', replaced: 'Replaced.',
      notYetAccepted: 'Saved, not yet accepted by Safaricom — test the key and secret.',
    },
    cert: { label: 'Certificate', hint: 'Needed only when adding an operator by password.' },
    operators: { switchToTest: (env: string) => `Switch to ${env === 'production' ? 'Production' : 'Sandbox'} mode to test this operator.` },
    shortcode: {
      label: 'Paybill or till number',
      knownAs: (name: string) => `Saved. Safaricom knows this shortcode as ${name}.`,
      unverified: 'Saved. Not yet verified with Safaricom.',
    },
    b2cApi: {
      title: 'B2C API version',
      auto: 'Automatic (recommended)',
      autoHint: 'Studio finds the version your app can use on the first send and keeps it.',
      v1: 'v1', v1Hint: 'Works with every Daraja app that has B2C.',
      v3: 'v3', v3Hint: 'Only if Safaricom enabled B2C v3 for your app.',
      detected: (version: string, when: string) => `Detected: ${version} (found ${when})`,
      saved: 'B2C API version saved.',
    },
    confirm: {
      org: 'Save the organisation details?',
      publicUrl: 'Save the public address?',
      switchMode: (env: string) => `Switch to ${env === 'production' ? 'Production' : 'Sandbox'}?`,
      saveShortcode: 'Save the shortcode?',
      replaceCreds: 'Replace the Daraja key and secret?',
      replacePasskey: 'Replace the STK passkey?',
      saveB2cApi: 'Save the B2C API version?',
      rotate: (name: string) => `Use a new password for ${name}?`,
      disable: (name: string) => `Turn off ${name}?`,
      add: (name: string) => `Add operator ${name}?`,
      allowlist: 'Change the Safaricom address list?',
      reveal: 'Show the callback secret?',
    },
  },
  toast: { close: 'Dismiss' },
  questionnaire: { of: (n: number, m: number) => `Question ${n} of ${m}`, next: 'Continue', back: 'Back', skip: 'Skip' },
  account: {
    menu: 'Account', title: 'Account', organisation: 'Organisation & shortcodes', shortcodes: 'Shortcodes', changePassword: 'Change password',
    deleteTitle: 'Delete this studio', deleteBody: 'Removes the organisation, its people, credentials and history. The install returns to first-run setup. This cannot be undone.',
    deleteButton: 'Delete this studio…', typeName: (name: string) => `Type ${name} to confirm`, deleted: 'Studio deleted.', ownerOnly: 'Only the owner can see this page.',
  },
  notPossiblePage: {
    title: 'Not possible via API',
    intro: 'Safaricom keeps these in its portal. Each card says why and where.',
    why: 'Why not here:',
    where: 'Where:',
    phone: 'Phone:',
    portalLink: 'Open the Safaricom portal',
  },
  notPossible: [
    { key: 'bank-withdrawal', title: 'Withdraw to the bank', what: 'Move money from M-Pesa to your bank account (normal or real-time).', why: 'Safaricom offers no API for organization withdrawals. Only the portal and USSD can start one.', portalPath: 'Transaction › Initiate Transaction › Organization Withdrawal From M-PESA', ussd: '*234*4#' },
    { key: 'utility-to-working', title: 'Move float from Utility to Working', what: 'Sweep collections from the Utility account into the Working (MMF) account.', why: 'The API command for this direction always fails with ResultCode 21. Safaricom API support confirmed it is manual only.', portalPath: 'Transaction › Initiate Transaction › Pay Bill Services – MMF Account Transfer', ussd: '*234# (full sweep)' },
    { key: 'operators', title: 'Create operators and give them roles', what: 'Add a person or API user in the Safaricom portal, set their access channel and roles.', why: 'Operator management has no API. Studio permissions sit on top of Safaricom roles; both must exist.', portalPath: 'Search › Organization Operator › Create, or › Detail › Role › Edit' },
    { key: 'operator-password', title: "Reset an operator's portal password", what: 'Send a new password to a portal operator.', why: 'No API. Studio can only take a new API password after you set it in the portal.', portalPath: 'Search › Organization Operator › Detail › Reset Password' },
    { key: 'org-profile', title: 'Organization profile and KYC', what: 'Contacts, nominated number, notification phone, Double Hakikisha, Reversal Initiation.', why: 'KYC data is portal-only. Studio keeps a read-only copy you type in once.', portalPath: 'Search › Organization › Details › KYC Info › Edit' },
    { key: 'bank-accounts', title: 'Bank accounts', what: 'Add, edit or remove the bank account linked to the shortcode.', why: 'No API.', portalPath: 'Search › My Organization › Bank Account' },
    { key: 'tills', title: 'Tills', what: 'Create or close a till under the organization.', why: 'No API.', portalPath: 'Search › My Organization › Till' },
    { key: 'revenue-settlement', title: 'Revenue settlement plans', what: 'Schedule settlements to the bank.', why: 'No API.', portalPath: 'Business Center › Revenue Settlement' },
    { key: 'tax-exemption', title: 'Tax exemption, accounting model, state tags', what: 'Organization-level tax and hierarchy settings.', why: 'No API.', portalPath: 'Search › Organization › Details' },
    { key: 'close-org', title: 'Close the organization', what: 'Permanently close the shortcode.', why: 'No API, by design.', portalPath: 'Search › Organization › Close' },
    { key: 'statement', title: "Safaricom's own account statement", what: 'The official statement with running balance per account.', why: 'No statement API. Studio History is its own ledger built from callbacks and pulls, not Safaricom’s statement.', portalPath: 'Transaction › Account Statement › Export' },
    { key: 'bulk-operators', title: 'Bulk operator creation', what: 'Upload a CSV of operators.', why: 'No API.', portalPath: 'Business Center › Bulk Task › Create Organization Operator' },
    { key: 'approval-switch', title: 'Operator Creation Approval Switch', what: "Portal's own maker-checker for creating operators.", why: 'Portal setting only.', portalPath: 'Search › Organization › Details › KYC Info' },
    { key: 'c2b-urls', title: 'Change registered paybill callback URLs', what: 'Point paybill payments at a different system after the first registration in production.', why: 'Production Daraja refuses to overwrite registered URLs. Delete and re-add them in the Daraja portal.', portalPath: 'Daraja portal › My Apps › your app › C2B URLs' },
    { key: 'portal-audit', title: 'Audit log of portal actions', what: 'What people did inside the Safaricom portal.', why: 'No API. Studio audits only what happens in studio.', portalPath: 'My Preference › Audit Log' },
  ] as NotPossibleItem[],
};
