// Copies the handful of line-md icons Studio uses out of the 1.4 MB icon set into src/icons/lineMd.ts,
// so the bundle carries only those. Run after changing NAMES: node scripts/icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const NAMES = [
  'home', 'document-report', 'arrow-right-circle', 'document-list', 'search', 'arrow-left-circle', 'arrow-down-circle',
  'cellphone', 'grid-3', 'file-document', 'calendar', 'speed', 'star', 'clipboard-check', 'list', 'account', 'cog',
  'alert-circle', 'menu', 'close', 'confirm-circle', 'lightbulb', 'loading-loop', 'arrow-left', 'arrow-right', 'logout',
  'confirm', 'alert', 'question-circle', 'chevron-down', 'chevron-up', 'chevron-right', 'chevron-left', 'external-link', 'plus', 'person-add', 'check-all',
];

const here = dirname(fileURLToPath(import.meta.url));
const set = JSON.parse(readFileSync(join(here, '..', 'node_modules', '@iconify-json', 'line-md', 'icons.json'), 'utf8'));
const out = {};
for (const n of NAMES) {
  const icon = set.icons[n] ?? (set.aliases?.[n] && set.icons[set.aliases[n].parent]);
  if (!icon) throw new Error(`line-md has no icon "${n}"`);
  out[n] = { body: icon.body, width: icon.width ?? set.width ?? 24, height: icon.height ?? set.height ?? 24 };
}
const ts = `// Generated by scripts/icons.mjs from @iconify-json/line-md (MIT). Do not edit by hand.
import type { IconifyIcon } from '@iconify/react';

export const ICONS = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, IconifyIcon>;

export type IconName = keyof typeof ICONS;
`;
writeFileSync(join(here, '..', 'src', 'icons', 'lineMd.ts'), ts);
console.log(`wrote ${NAMES.length} icons`);
